### ISSUE TITLE
Implement Address Bar and User Modal Components

### ISSUE THREAD

**Issue by Oshioke-Salaki** [horuslabsio/seamlessui#5]
## Description
Develop a fully functional Address Bar component as per the design provided in the [FIGMA FILE](https://www.figma.com/design/pL9HcD5saTR6TtMsZYyS7z/STARKNET-UI-KITS?node-id=0-1&node-type=canvas&t=gT1lFVCNijoXRGlC-0) along with all it’s variants. This component shows the connect user’s [starknet.id](http://starknet.id/) name and pfp or address, and pops up a user modal on click.

## Requirements

- Design: Follow the provided Figma design precisely for both light and dark mode. Ensure that the component is fully responsive across different screen sizes.
- Style Guide: Adhere strictly to the project’s existing style guide for consistency in UI and UX.
- Functionality: The component should be fully functional, allowing users to seamlessly switch networks.

After building the component, create a sub-route in the `preview` route for the component and display each of it’s variant for easy testing. 

## Guidance
There is an already implemented Connect Button component which can serve as a reference for styling, functionality and previewing.

## Note
No other external dependencies should be installed other than the ones already provided.

**Comment by Calebux** [comment]
w

**Comment by CollinsC1O** [comment]
@Oshioke-Salaki I will love to work on this please

**Comment by martinvibes** [comment]
hello @Oshioke-Salaki i would love to work on this :)

**Comment by dev-chinx** [comment]
can i work on this issue @Oshioke-Salaki

**Comment by ShantelPeters** [comment]
Hello @Oshioke-Salaki i will like to work on this issue

**Comment by Kaminar-i** [comment]
can i have this @Oshioke-Salaki

**Comment by Ugo-X** [comment]
I would love to work on this issue.

Here is how i plan to tackle it:

I will create the Address Bar and User Modal components, focusing on integrating user information and responsiveness. 

  

- **Step 1:** I will analyze the Figma design for the Address Bar to understand how it should display the user's starknet.id name, profile picture, or address. 

  

- **Step 2:** I will set up the component structure and pass the relevant user data as props. 

  

- **Step 3:** I will implement the pop-up modal functionality that displays user details when the Address Bar is clicked. 

  

- **Step 4:** I will ensure the component is responsive by using CSS techniques that accommodate different screen sizes. 

  

- **Step 5:** I will apply styles consistent with the project’s style guide, ensuring a uniform look and feel. 

  

- **Step 6:** I will create a sub-route in the preview route for this component, allowing for easy testing and display of its variants. 

  

- **Step 7:** I will test the Address Bar and User Modal components to ensure they work correctly, including the network switching functionality and the modal display.

**Comment by Oshioke-Salaki** [comment]
Hello guys, everyone needs to apply for issues via, The OnlyDust Platform. So please do that and i will assign. Only applications done via OD will be considered.

**Comment by Gift-Naomi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
I am a web3 developer/ Frontend developer


### How I plan on tackling this issue
1. **Component Setup**: Build the Address Bar component following the Figma design for both light/dark modes and ensure responsiveness across screen sizes. Reuse styles from the Connect Button for consistency.

2. **Functionality**: Implement the logic to display the connected user’s Starknet ID (name, pfp, or address) and trigger a modal on click for user interaction. Handle network switching within this modal.

3. **Preview Route**: Create a new sub-route under the preview route to showcase all variants of the Address Bar component for testing.

**Comment by gidson5** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
I'm an experienced front end developer

### How I plan on tackling this issue
To solve this issue i'd do this

I'll first of all check the Figma Design (ie review the Figma file carefully to understand the exact design, layout, icons, and styles for the address bar in both light and dark modes.)
Next, I'll identify which data will be passed as props, such as the connected user’s starknet.id, pfp, and address. I'll plan the structure for the user modal that pops up on click, showing additional user details. I'll ensure each variant (e.g., with and without PFP, address-only state) is accounted for.
I'll then implement the Address Bar component using HTML, CSS, or a styling solution like styled-components (if using React). I'll use CSS variables or theme providers to support theme switching. I'll also make sure the component layout adjusts smoothly across different screen sizes using CSS Grid or Flexbox. I'll create the user modal that pops up on click, including animations or transitions for a smooth user experience.
I'll fetch or pass the user’s starknet.id or address via props or by connecting to a backend or Starknet-related API. I'll integrate network switching logic, using libraries like web3.js or ethers.js. I'll make sure the UI updates accordingly when the network is changed. I'll ensure that clicking the address bar opens the user modal and that it can close smoothly.
5.I'll then create a sub-route within the preview route where all variants of the Address Bar component are displayed for easy testing. Also, I'll test the component in various screen sizes and modes to ensure responsiveness and functionality.

**Comment by addegbenga** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
I am a frontend engineer with over 5 years experience building webapps.

### How I plan on tackling this issue
I will tackle this issue by:
- Creating a newly functional address bar that matches the figma design.
- Making sure to use the existing UI library to accomplish this task.
- Add a preview component to display the newly created components and all the variants based on the figma design.

ETA: 48hrs

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
Hello @Oshioke-Salaki I'm a front-end and a blockchain developer. I did love work on this please 

### How I plan on tackling this issue
I
